### PR TITLE
New feature: Premium is added test

### PR DESCRIPTION
**Pull request by dert-test**

### CODE REVIEW

**Review by kxu12348760 — COMMENTED** [review]
For node: org.springframework.samples.petclinic.model.MonetizablePerson
kxu12348760's comment is: test comment
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/33/MntsShrmp_Petclinic-DEMO_33_from_premiumFeature.dert/org.springframework.samples.petclinic.model.MonetizablePerson)

**Review by AtaYurtsever — COMMENTED** [review]
For node: org.springframework.samples.petclinic.visit.VisitRepository
AtaYurtsever's comment is: test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/33/MntsShrmp_Petclinic-DEMO_33_from_premiumFeature.dert/org.springframework.samples.petclinic.visit.VisitRepository)

**Review by dert-test — COMMENTED** [review]
For node: org.springframework.samples.petclinic.owner.MonetizableRepository
dert-test's comment is: test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/33/MntsShrmp_Petclinic-DEMO_33_from_premiumFeature.dert/org.springframework.samples.petclinic.owner.MonetizableRepository)

**Review by dert-test — COMMENTED** [review]
For node: org.springframework.samples.petclinic.owner.MonetizableRepository
dert-test's comment is: test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/33/MntsShrmp_Petclinic-DEMO_33_from_premiumFeature.dert/org.springframework.samples.petclinic.owner.MonetizableRepository)

**Pull request closed without merging**
