### PR TITLE
Add method

### PR DESCRIPTION
**Pull request by cankattilki**

### CODE REVIEW

**Review by onsah — COMMENTED** [review]
For node: javax.cache.spi.CachingProvider
onsah's comment is: Test
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.OptionalFeature
DilrubaSultan's comment is: Hey
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.spi.CachingProvider
DilrubaSultan's comment is: Test
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.Cache
DilrubaSultan's comment is: This is a new comment.
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert)

**Review by MntShmrp — COMMENTED** [review]
For node: javax.cache.Cache
MntShmrp's comment is: This is a new comment.
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert)

**Review by DilrubaSultan — COMMENTED** [review]
For node: org.springframework.dao.DataAccessException
DilrubaSultan's comment is: Let's try this one
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/org.springframework.dao.DataAccessException)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.integration.CompletionListener
DilrubaSultan's comment is: Test
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.integration.CompletionListener)

**Review by MntShmrp — COMMENTED** [review]
For node: javax.cache.event.EventType
MntShmrp's comment is: Test1
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.event.EventType)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.CacheException
's comment is: Hey1
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.CacheException)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.processor.EntryProcessor
DilrubaSultan's comment is: hello
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.processor.EntryProcessor)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.event.CacheEntryEventFilter
DilrubaSultan's comment is: Test1
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.event.CacheEntryEventFilter)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.processor.EntryProcessor
DilrubaSultan's comment is: Test2
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.processor.EntryProcessor)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.event.CacheEntryListenerException
DilrubaSultan's comment is: Test3
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.event.CacheEntryListenerException)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.Configuration
DilrubaSultan's comment is: test
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.Configuration)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.processor.EntryProcessor
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.processor.EntryProcessor)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.processor.EntryProcessorResult
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.processor.EntryProcessorResult)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.Factory
DilrubaSultan's comment is: Hey Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.Factory)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.OptionalFeature
DilrubaSultan's comment is: test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.OptionalFeature)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.processor.EntryProcessor
DilrubaSultan's comment is: Test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.processor.EntryProcessor)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.CacheEntryListenerConfiguration
DilrubaSultan's comment is: Hey
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.CacheEntryListenerConfiguration)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.CacheEntryListenerConfiguration
DilrubaSultan's comment is: 
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.CacheEntryListenerConfiguration)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.CacheEntryListenerConfiguration
DilrubaSultan's comment is: Test2
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.CacheEntryListenerConfiguration)

**Review by DilrubaSultan — COMMENTED** [review]
For node: javax.cache.configuration.CacheEntryListenerConfiguration
DilrubaSultan's comment is: Test597
Access it through, [this link](http://localhost:3001/MntsShrmp/Petclinic-DEMO/dertfile/9/MntsShrmp_Petclinic-DEMO_9_from_addMethod.dert/javax.cache.configuration.CacheEntryListenerConfiguration)

**Pull request closed without merging**
