### PR TITLE
New feature: Premium is added

### PR DESCRIPTION
**Pull request by AtaYurtsever**

### CODE REVIEW

**Review by AtaYurtsever — COMMENTED** [review]
For node: org.springframework.samples.petclinic.model.MonetizablePerson
AtaYurtsever's comment is: Nice we needed this!!!
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/30/MntsShrmp_Petclinic-DEMO_30_from_premiumFeature.dert/org.springframework.samples.petclinic.model.MonetizablePerson)

**Review by onsah — APPROVED** [review]
For node: org.springframework.samples.petclinic.model.MonetizablePerson
onsah's comment is: Good 
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/30/MntsShrmp_Petclinic-DEMO_30_from_premiumFeature.dert/org.springframework.samples.petclinic.model.MonetizablePerson)

**Review by onsah — CHANGES_REQUESTED** [review]
For node: org.springframework.samples.petclinic.model.MonetizablePerson
onsah's comment is: what a horrible code
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/30/MntsShrmp_Petclinic-DEMO_30_from_premiumFeature.dert/org.springframework.samples.petclinic.model.MonetizablePerson)

**Review by AtaYurtsever — COMMENTED** [review]
For node: org.springframework.samples.petclinic.visit.VisitRepository
AtaYurtsever's comment is: test
Access it through, [this link](http://139.179.38.81:3001/MntsShrmp/Petclinic-DEMO/dertfile/30/MntsShrmp_Petclinic-DEMO_30_from_premiumFeature.dert/org.springframework.samples.petclinic.visit.VisitRepository)

**Pull request closed without merging**
